Search.appendIndex(
    [
                {
            "fqsen": "\\Db",
            "name": "Db",
            "summary": "",
            "url": "classes/Db.html"
        },                {
            "fqsen": "\\Db\u003A\u003Apropoj\u0028\u0029",
            "name": "propoj",
            "summary": "P\u0159ipoj\u00ED\u0020se\u0020k\u0020datab\u00E1zi\u0020pomoc\u00ED\u0020dan\u00FDch\u0020\u00FAdaj\u016F",
            "url": "classes/Db.html#method_propoj"
        },                {
            "fqsen": "\\Db\u003A\u003AexecuteStatement\u0028\u0029",
            "name": "executeStatement",
            "summary": "Spust\u00ED\u0020dotaz\u0020a\u0020vr\u00E1t\u00ED\u0020PDO\u0020statement",
            "url": "classes/Db.html#method_executeStatement"
        },                {
            "fqsen": "\\Db\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "Spust\u00ED\u0020dotaz\u0020a\u0020vr\u00E1t\u00ED\u0020po\u010Det\u0020ovlivn\u011Bn\u00FDch\u0020\u0159\u00E1dk\u016F.\u0020D\u00E1le\u0020se\u0020p\u0159ed\u00E1\u0020libovoln\u00FD\u0020po\u010Det\u0020dal\u0161\u00EDch\u0020parametr\u016F.",
            "url": "classes/Db.html#method_query"
        },                {
            "fqsen": "\\Db\u003A\u003AquerySingle\u0028\u0029",
            "name": "querySingle",
            "summary": "Spust\u00ED\u0020dotaz\u0020a\u0020vr\u00E1t\u00ED\u0020z\u0020n\u011Bj\u0020prvn\u00ED\u0020sloupec\u0020prvn\u00EDho\u0020\u0159\u00E1dku.\u0020D\u00E1le\u0020se\u0020p\u0159ed\u00E1\u0020libovoln\u00FD\u0020po\u010Det\u0020dal\u0161\u00EDch\u0020parametr\u016F.",
            "url": "classes/Db.html#method_querySingle"
        },                {
            "fqsen": "\\Db\u003A\u003AqueryOne\u0028\u0029",
            "name": "queryOne",
            "summary": "Spust\u00ED\u0020dotaz\u0020a\u0020vr\u00E1t\u00ED\u0020z\u0020n\u011Bj\u0020prvn\u00ED\u0020\u0159\u00E1dek.\u0020D\u00E1le\u0020se\u0020p\u0159ed\u00E1\u0020libovoln\u00FD\u0020po\u010Det\u0020dal\u0161\u00EDch\u0020parametr\u016F.",
            "url": "classes/Db.html#method_queryOne"
        },                {
            "fqsen": "\\Db\u003A\u003AqueryAll\u0028\u0029",
            "name": "queryAll",
            "summary": "Spust\u00ED\u0020dotaz\u0020a\u0020vr\u00E1t\u00ED\u0020v\u0161echny\u0020jeho\u0020\u0159\u00E1dky\u0020jako\u0020pole\u0020asociativn\u00EDch\u0020pol\u00ED.\u0020D\u00E1le\u0020se\u0020p\u0159ed\u00E1\u0020libovoln\u00FD\u0020po\u010Det\u0020dal\u0161\u00EDch\u0020parametr\u016F.",
            "url": "classes/Db.html#method_queryAll"
        },                {
            "fqsen": "\\Db\u003A\u003Ainsert\u0028\u0029",
            "name": "insert",
            "summary": "Umo\u017E\u0148uje\u0020snadn\u00E9\u0020vlo\u017Een\u00ED\u0020z\u00E1znamu\u0020do\u0020datab\u00E1ze\u0020pomoc\u00ED\u0020asociativn\u00EDho\u0020pole",
            "url": "classes/Db.html#method_insert"
        },                {
            "fqsen": "\\Db\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Umo\u017E\u0148uje\u0020snadnou\u0020modifikaci\u0020z\u00E1znamu\u0020v\u0020datab\u00E1zi\u0020pomoc\u00ED\u0020asociativn\u00EDho\u0020pole",
            "url": "classes/Db.html#method_update"
        },                {
            "fqsen": "\\Db\u003A\u003AgetLastId\u0028\u0029",
            "name": "getLastId",
            "summary": "Vr\u00E1t\u00ED\u0020posledn\u00ED\u0020ID\u0020posledn\u00EDho\u0020z\u00E1znamu\u0020vlo\u017Een\u00E9ho\u0020pomoc\u00ED\u0020INSERT",
            "url": "classes/Db.html#method_getLastId"
        },                {
            "fqsen": "\\Db\u003A\u003Aquote\u0028\u0029",
            "name": "quote",
            "summary": "O\u0161et\u0159\u00ED\u0020string\u0020proti\u0020SQL\u0020injekci",
            "url": "classes/Db.html#method_quote"
        },                {
            "fqsen": "\\Db\u003A\u003AcheckIdentifiers\u0028\u0029",
            "name": "checkIdentifiers",
            "summary": "Zkontroluje,\u0020zda\u0020identifik\u00E1tory\u0020odpov\u00EDdaj\u00ED\u0020form\u00E1tu\u0020identifik\u00E1tor\u016F",
            "url": "classes/Db.html#method_checkIdentifiers"
        },                {
            "fqsen": "\\Db\u003A\u003A\u0024spojeni",
            "name": "spojeni",
            "summary": "",
            "url": "classes/Db.html#property_spojeni"
        },                {
            "fqsen": "\\Db\u003A\u003A\u0024nastaveni",
            "name": "nastaveni",
            "summary": "",
            "url": "classes/Db.html#property_nastaveni"
        },                {
            "fqsen": "\\DB_HOST",
            "name": "DB_HOST",
            "summary": "",
            "url": "namespaces/default.html#constant_DB_HOST"
        },                {
            "fqsen": "\\DB_NAME",
            "name": "DB_NAME",
            "summary": "",
            "url": "namespaces/default.html#constant_DB_NAME"
        },                {
            "fqsen": "\\DB_USERNAME",
            "name": "DB_USERNAME",
            "summary": "",
            "url": "namespaces/default.html#constant_DB_USERNAME"
        },                {
            "fqsen": "\\DB_PASSWORD",
            "name": "DB_PASSWORD",
            "summary": "",
            "url": "namespaces/default.html#constant_DB_PASSWORD"
        },                {
            "fqsen": "\\WidgetUzivatelPrihlasen\u0028\u0029",
            "name": "WidgetUzivatelPrihlasen",
            "summary": "",
            "url": "namespaces/default.html#function_WidgetUzivatelPrihlasen"
        },                {
            "fqsen": "\\WidgetUzivatelUcet\u0028\u0029",
            "name": "WidgetUzivatelUcet",
            "summary": "",
            "url": "namespaces/default.html#function_WidgetUzivatelUcet"
        },                {
            "fqsen": "\\overPrihlaseni\u0028\u0029",
            "name": "overPrihlaseni",
            "summary": "funkce\u0020pro\u0020overeni\u0020zda\u0020je\u0020uzivatel\u0020prihlaseny\nkdyz\u0020neni\u0020prihlaseny\u0020vratime\u0020FALSE",
            "url": "namespaces/default.html#function_overPrihlaseni"
        },                {
            "fqsen": "\\WidgetUzivatelPrihlasovaciFormular\u0028\u0029",
            "name": "WidgetUzivatelPrihlasovaciFormular",
            "summary": "",
            "url": "namespaces/default.html#function_WidgetUzivatelPrihlasovaciFormular"
        },                {
            "fqsen": "\\WidgetUzivatelRegistracniFormular\u0028\u0029",
            "name": "WidgetUzivatelRegistracniFormular",
            "summary": "",
            "url": "namespaces/default.html#function_WidgetUzivatelRegistracniFormular"
        },                {
            "fqsen": "\\WidgetUzivatelUcetUvod\u0028\u0029",
            "name": "WidgetUzivatelUcetUvod",
            "summary": "",
            "url": "namespaces/default.html#function_WidgetUzivatelUcetUvod"
        },                {
            "fqsen": "\\WidgetUzivatelEditacniFormular\u0028\u0029",
            "name": "WidgetUzivatelEditacniFormular",
            "summary": "",
            "url": "namespaces/default.html#function_WidgetUzivatelEditacniFormular"
        },                {
            "fqsen": "\\WidgetAdminiProdukt\u0028\u0029",
            "name": "WidgetAdminiProdukt",
            "summary": "",
            "url": "namespaces/default.html#function_WidgetAdminiProdukt"
        },                {
            "fqsen": "\\WidgetAdminiProduktFormular\u0028\u0029",
            "name": "WidgetAdminiProduktFormular",
            "summary": "",
            "url": "namespaces/default.html#function_WidgetAdminiProduktFormular"
        },                {
            "fqsen": "\\WidgetAdminUzivatele\u0028\u0029",
            "name": "WidgetAdminUzivatele",
            "summary": "",
            "url": "namespaces/default.html#function_WidgetAdminUzivatele"
        },                {
            "fqsen": "\\WidgetNabidkaProduktu\u0028\u0029",
            "name": "WidgetNabidkaProduktu",
            "summary": "",
            "url": "namespaces/default.html#function_WidgetNabidkaProduktu"
        },                {
            "fqsen": "\\WidgetObjednavkaProduktu\u0028\u0029",
            "name": "WidgetObjednavkaProduktu",
            "summary": "",
            "url": "namespaces/default.html#function_WidgetObjednavkaProduktu"
        },                {
            "fqsen": "\\WidgetObjednavkaRekapitulace\u0028\u0029",
            "name": "WidgetObjednavkaRekapitulace",
            "summary": "",
            "url": "namespaces/default.html#function_WidgetObjednavkaRekapitulace"
        },                {
            "fqsen": "\\WidgetAdminiKontrakt\u0028\u0029",
            "name": "WidgetAdminiKontrakt",
            "summary": "",
            "url": "namespaces/default.html#function_WidgetAdminiKontrakt"
        },                {
            "fqsen": "\\nactiTridu\u0028\u0029",
            "name": "nactiTridu",
            "summary": "",
            "url": "namespaces/default.html#function_nactiTridu"
        },                {
            "fqsen": "\\Captcha",
            "name": "Captcha",
            "summary": "",
            "url": "classes/Captcha.html"
        },                {
            "fqsen": "\\Captcha\u003A\u003Avypis\u0028\u0029",
            "name": "vypis",
            "summary": "V\u00FDpis\u0020frmularoveho\npole",
            "url": "classes/Captcha.html#method_vypis"
        },                {
            "fqsen": "\\Captcha\u003A\u003Aover\u0028\u0029",
            "name": "over",
            "summary": "Metoda\u0020pro\u0020ov\u011B\u0159en\u00ED",
            "url": "classes/Captcha.html#method_over"
        },                {
            "fqsen": "\\CaptchaRok",
            "name": "CaptchaRok",
            "summary": "opat\u0159eni\u0020proti\u0020spamu",
            "url": "classes/CaptchaRok.html"
        },                {
            "fqsen": "\\CaptchaRok\u003A\u003Avypis\u0028\u0029",
            "name": "vypis",
            "summary": "V\u00FDpis\u0020frmularoveho\npole",
            "url": "classes/CaptchaRok.html#method_vypis"
        },                {
            "fqsen": "\\CaptchaRok\u003A\u003Aover\u0028\u0029",
            "name": "over",
            "summary": "Metoda\u0020pro\u0020ov\u011B\u0159en\u00ED",
            "url": "classes/CaptchaRok.html#method_over"
        },                {
            "fqsen": "\\Constanty",
            "name": "Constanty",
            "summary": "",
            "url": "classes/Constanty.html"
        },                {
            "fqsen": "\\Constanty\u003A\u003AADMINISTRATOR_WEBU",
            "name": "ADMINISTRATOR_WEBU",
            "summary": "statut\u0020prihlaseneho\nConstanty\u003A\u003APOZICE_1\u003B",
            "url": "classes/Constanty.html#constant_ADMINISTRATOR_WEBU"
        },                {
            "fqsen": "\\Constanty\u003A\u003AUZIVATEL_WEBU",
            "name": "UZIVATEL_WEBU",
            "summary": "",
            "url": "classes/Constanty.html#constant_UZIVATEL_WEBU"
        },                {
            "fqsen": "\\Constanty\u003A\u003ANEPRIHLASENY_UZIVATEL_WEBU",
            "name": "NEPRIHLASENY_UZIVATEL_WEBU",
            "summary": "",
            "url": "classes/Constanty.html#constant_NEPRIHLASENY_UZIVATEL_WEBU"
        },                {
            "fqsen": "\\Constanty\u003A\u003APOZICE_1",
            "name": "POZICE_1",
            "summary": "",
            "url": "classes/Constanty.html#constant_POZICE_1"
        },                {
            "fqsen": "\\Constanty\u003A\u003APOZICE_0",
            "name": "POZICE_0",
            "summary": "",
            "url": "classes/Constanty.html#constant_POZICE_0"
        },                {
            "fqsen": "\\InfoText",
            "name": "InfoText",
            "summary": "",
            "url": "classes/InfoText.html"
        },                {
            "fqsen": "\\InfoText\u003A\u003Aprihlaseny\u0028\u0029",
            "name": "prihlaseny",
            "summary": "",
            "url": "classes/InfoText.html#method_prihlaseny"
        },                {
            "fqsen": "\\InfoText\u003A\u003Aneprihlaseny\u0028\u0029",
            "name": "neprihlaseny",
            "summary": "",
            "url": "classes/InfoText.html#method_neprihlaseny"
        },                {
            "fqsen": "\\InfoText\u003A\u003APRIHL",
            "name": "PRIHL",
            "summary": "",
            "url": "classes/InfoText.html#constant_PRIHL"
        },                {
            "fqsen": "\\InfoText\u003A\u003ANEPRIHL",
            "name": "NEPRIHL",
            "summary": "",
            "url": "classes/InfoText.html#constant_NEPRIHL"
        },                {
            "fqsen": "\\Brana",
            "name": "Brana",
            "summary": "",
            "url": "classes/Brana.html"
        },                {
            "fqsen": "\\Brana\u003A\u003Azpracuj\u0028\u0029",
            "name": "zpracuj",
            "summary": "Simuluje\u0020zpracov\u00E1n\u00ED\u0020objedn\u00E1vky\u0020platebn\u00ED\u0020br\u00E1nou,\u0020v\u0020na\u0161em\u0020p\u0159\u00EDpad\u011B\u0020jen\u0020data\u0020vyp\u00ED\u0161e\u0020do\u0020tabulky",
            "url": "classes/Brana.html#method_zpracuj"
        },                {
            "fqsen": "\\Objednavka",
            "name": "Objednavka",
            "summary": "objedn\u00E1vku\u0020produktu,\u0020kter\u00E1\u0020je\u0020implementov\u00E1na\u0020podle\u0020rozhran\u00ED",
            "url": "classes/Objednavka.html"
        },                {
            "fqsen": "\\Objednavka\u003A\u003AnastavIdUzivatel\u0028\u0029",
            "name": "nastavIdUzivatel",
            "summary": "Nastav\u00ED\u0020id\u0020uzivatele",
            "url": "classes/Objednavka.html#method_nastavIdUzivatel"
        },                {
            "fqsen": "\\Objednavka\u003A\u003AnastavIdproduktu\u0028\u0029",
            "name": "nastavIdproduktu",
            "summary": "nastavi\u0020id\u0020produktu",
            "url": "classes/Objednavka.html#method_nastavIdproduktu"
        },                {
            "fqsen": "\\Objednavka\u003A\u003AnastavNazev\u0028\u0029",
            "name": "nastavNazev",
            "summary": "nastavi\u0020nazev",
            "url": "classes/Objednavka.html#method_nastavNazev"
        },                {
            "fqsen": "\\Objednavka\u003A\u003AnastavCastka\u0028\u0029",
            "name": "nastavCastka",
            "summary": "nastavi\u0020castka",
            "url": "classes/Objednavka.html#method_nastavCastka"
        },                {
            "fqsen": "\\Objednavka\u003A\u003AnastavPredmet\u0028\u0029",
            "name": "nastavPredmet",
            "summary": "nastavi\u0020predmet",
            "url": "classes/Objednavka.html#method_nastavPredmet"
        },                {
            "fqsen": "\\Objednavka\u003A\u003AnastavOddata\u0028\u0029",
            "name": "nastavOddata",
            "summary": "Nastav\u00ED\u0020oddata",
            "url": "classes/Objednavka.html#method_nastavOddata"
        },                {
            "fqsen": "\\Objednavka\u003A\u003AnastavDodata\u0028\u0029",
            "name": "nastavDodata",
            "summary": "Nastav\u00ED\u0020dodata",
            "url": "classes/Objednavka.html#method_nastavDodata"
        },                {
            "fqsen": "\\Objednavka\u003A\u003AvratIdUzivatel\u0028\u0029",
            "name": "vratIdUzivatel",
            "summary": "Vr\u00E1t\u00ED\u0020iduzivatel",
            "url": "classes/Objednavka.html#method_vratIdUzivatel"
        },                {
            "fqsen": "\\Objednavka\u003A\u003AvratIdproduktu\u0028\u0029",
            "name": "vratIdproduktu",
            "summary": "Vr\u00E1t\u00ED\u0020idproduktu",
            "url": "classes/Objednavka.html#method_vratIdproduktu"
        },                {
            "fqsen": "\\Objednavka\u003A\u003AvratNazev\u0028\u0029",
            "name": "vratNazev",
            "summary": "Vr\u00E1t\u00ED\u0020nazev",
            "url": "classes/Objednavka.html#method_vratNazev"
        },                {
            "fqsen": "\\Objednavka\u003A\u003AvratCastka\u0028\u0029",
            "name": "vratCastka",
            "summary": "Vr\u00E1t\u00ED\u0020castka",
            "url": "classes/Objednavka.html#method_vratCastka"
        },                {
            "fqsen": "\\Objednavka\u003A\u003AvratPredmet\u0028\u0029",
            "name": "vratPredmet",
            "summary": "Vr\u00E1t\u00ED\u0020predmet",
            "url": "classes/Objednavka.html#method_vratPredmet"
        },                {
            "fqsen": "\\Objednavka\u003A\u003AvratOddata\u0028\u0029",
            "name": "vratOddata",
            "summary": "Vr\u00E1t\u00ED\u0020oddata",
            "url": "classes/Objednavka.html#method_vratOddata"
        },                {
            "fqsen": "\\Objednavka\u003A\u003AvratDOdata\u0028\u0029",
            "name": "vratDOdata",
            "summary": "Vr\u00E1t\u00ED\u0020dodata",
            "url": "classes/Objednavka.html#method_vratDOdata"
        },                {
            "fqsen": "\\Objednavka\u003A\u003A\u0024idUzivatel",
            "name": "idUzivatel",
            "summary": "",
            "url": "classes/Objednavka.html#property_idUzivatel"
        },                {
            "fqsen": "\\Objednavka\u003A\u003A\u0024idProduktu",
            "name": "idProduktu",
            "summary": "",
            "url": "classes/Objednavka.html#property_idProduktu"
        },                {
            "fqsen": "\\Objednavka\u003A\u003A\u0024nazev",
            "name": "nazev",
            "summary": "",
            "url": "classes/Objednavka.html#property_nazev"
        },                {
            "fqsen": "\\Objednavka\u003A\u003A\u0024castka",
            "name": "castka",
            "summary": "",
            "url": "classes/Objednavka.html#property_castka"
        },                {
            "fqsen": "\\Objednavka\u003A\u003A\u0024predmet",
            "name": "predmet",
            "summary": "",
            "url": "classes/Objednavka.html#property_predmet"
        },                {
            "fqsen": "\\Objednavka\u003A\u003A\u0024oddata",
            "name": "oddata",
            "summary": "",
            "url": "classes/Objednavka.html#property_oddata"
        },                {
            "fqsen": "\\Objednavka\u003A\u003A\u0024dodata",
            "name": "dodata",
            "summary": "",
            "url": "classes/Objednavka.html#property_dodata"
        },                {
            "fqsen": "\\Presmeruj",
            "name": "Presmeruj",
            "summary": "",
            "url": "classes/Presmeruj.html"
        },                {
            "fqsen": "\\Presmeruj\u003A\u003ApresmerovaniNaStranku\u0028\u0029",
            "name": "presmerovaniNaStranku",
            "summary": "funkce\u0020pro\u0020presmerovani",
            "url": "classes/Presmeruj.html#method_presmerovaniNaStranku"
        },                {
            "fqsen": "\\RozhraniObjednavky",
            "name": "RozhraniObjednavky",
            "summary": "rozhran\u00ED\u0020implementovane\u0020v\u0020objedn\u00E1vce",
            "url": "classes/RozhraniObjednavky.html"
        },                {
            "fqsen": "\\RozhraniObjednavky\u003A\u003AvratIdUzivatel\u0028\u0029",
            "name": "vratIdUzivatel",
            "summary": "",
            "url": "classes/RozhraniObjednavky.html#method_vratIdUzivatel"
        },                {
            "fqsen": "\\RozhraniObjednavky\u003A\u003AvratIdproduktu\u0028\u0029",
            "name": "vratIdproduktu",
            "summary": "",
            "url": "classes/RozhraniObjednavky.html#method_vratIdproduktu"
        },                {
            "fqsen": "\\RozhraniObjednavky\u003A\u003AvratNazev\u0028\u0029",
            "name": "vratNazev",
            "summary": "",
            "url": "classes/RozhraniObjednavky.html#method_vratNazev"
        },                {
            "fqsen": "\\RozhraniObjednavky\u003A\u003AvratCastka\u0028\u0029",
            "name": "vratCastka",
            "summary": "",
            "url": "classes/RozhraniObjednavky.html#method_vratCastka"
        },                {
            "fqsen": "\\RozhraniObjednavky\u003A\u003AvratPredmet\u0028\u0029",
            "name": "vratPredmet",
            "summary": "",
            "url": "classes/RozhraniObjednavky.html#method_vratPredmet"
        },                {
            "fqsen": "\\RozhraniObjednavky\u003A\u003AvratOddata\u0028\u0029",
            "name": "vratOddata",
            "summary": "",
            "url": "classes/RozhraniObjednavky.html#method_vratOddata"
        },                {
            "fqsen": "\\RozhraniObjednavky\u003A\u003AvratDodata\u0028\u0029",
            "name": "vratDodata",
            "summary": "",
            "url": "classes/RozhraniObjednavky.html#method_vratDodata"
        },                {
            "fqsen": "\\Zaklad\\adminProdukt\\Produkt",
            "name": "Produkt",
            "summary": "",
            "url": "classes/Zaklad-adminProdukt-Produkt.html"
        },                {
            "fqsen": "\\Zaklad\\adminProdukt\\Produkt\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Zaklad-adminProdukt-Produkt.html#method___construct"
        },                {
            "fqsen": "\\Zaklad\\adminProdukt\\Produkt\u003A\u003AobjednejKontrakt\u0028\u0029",
            "name": "objednejKontrakt",
            "summary": "funkce\u0020pro\u0020vypsani\u0020formulare",
            "url": "classes/Zaklad-adminProdukt-Produkt.html#method_objednejKontrakt"
        },                {
            "fqsen": "\\Zaklad\\adminProdukt\\Produkt\u003A\u003ApridejKontrakt\u0028\u0029",
            "name": "pridejKontrakt",
            "summary": "zapise\u0020do\u0020databaze\npredana\u0020a\u0020zvalidovana\u0020data\nz\u0020formulre",
            "url": "classes/Zaklad-adminProdukt-Produkt.html#method_pridejKontrakt"
        },                {
            "fqsen": "\\Zaklad\\adminProdukt\\Produkt\u003A\u003AnabidniProdukty\u0028\u0029",
            "name": "nabidniProdukty",
            "summary": "vypise\u0020vsechny\u0020produkty\u0020z\u0020databaze\nnab\u00EDdka\u0020produktu",
            "url": "classes/Zaklad-adminProdukt-Produkt.html#method_nabidniProdukty"
        },                {
            "fqsen": "\\Zaklad\\adminProdukt\\Produkt\u003A\u003AvypisProdukty\u0028\u0029",
            "name": "vypisProdukty",
            "summary": "funkce\u0020vypise\u0020vsechny\u0020produkty\na\u0020vlozi\u0020ID\u0020produktu\u0020do\u0020formulare\npro\u0020editaci\u0020nebo\u0020smazani",
            "url": "classes/Zaklad-adminProdukt-Produkt.html#method_vypisProdukty"
        },                {
            "fqsen": "\\Zaklad\\adminProdukt\\Produkt\u003A\u003AformularProdukt\u0028\u0029",
            "name": "formularProdukt",
            "summary": "funkce\u0020pro\u0020vypsani\u0020formulare\npro\u0020vlozeni\u0020a\u0020editaci\u0020produktu",
            "url": "classes/Zaklad-adminProdukt-Produkt.html#method_formularProdukt"
        },                {
            "fqsen": "\\Zaklad\\adminProdukt\\Produkt\u003A\u003Apridej\u0028\u0029",
            "name": "pridej",
            "summary": "P\u0159id\u00E1\u0020do\u0020datab\u00E1ze\u0020nov\u00FD\u0020produkt",
            "url": "classes/Zaklad-adminProdukt-Produkt.html#method_pridej"
        },                {
            "fqsen": "\\Zaklad\\adminProdukt\\Produkt\u003A\u003Anacti\u0028\u0029",
            "name": "nacti",
            "summary": "Na\u010Dte\u0020a\u0020vr\u00E1t\u00ED\u0020produkt\u0020podle\u0020jeho\u0020id",
            "url": "classes/Zaklad-adminProdukt-Produkt.html#method_nacti"
        },                {
            "fqsen": "\\Zaklad\\adminProdukt\\Produkt\u003A\u003Auprav\u0028\u0029",
            "name": "uprav",
            "summary": "Uprav\u00ED\u0020v\u0020datab\u00E1zi\u0020z\u00E1znam\u0020\u002D\u0020produkt\u0020s\u0020dan\u00FDm\u0020id",
            "url": "classes/Zaklad-adminProdukt-Produkt.html#method_uprav"
        },                {
            "fqsen": "\\Zaklad\\adminProdukt\\Produkt\u003A\u003Aodstran\u0028\u0029",
            "name": "odstran",
            "summary": "Odstran\u00ED\u0020produkt\u0020s\u0020dan\u00FDm\u0020id",
            "url": "classes/Zaklad-adminProdukt-Produkt.html#method_odstran"
        },                {
            "fqsen": "\\Zaklad\\adminProdukt\\Produkt\u003A\u003A\u0024produkty",
            "name": "produkty",
            "summary": "",
            "url": "classes/Zaklad-adminProdukt-Produkt.html#property_produkty"
        },                {
            "fqsen": "\\Zaklad\\adminProdukt\\Produkt\u003A\u003A\u0024statut",
            "name": "statut",
            "summary": "",
            "url": "classes/Zaklad-adminProdukt-Produkt.html#property_statut"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel",
            "name": "Uzivatel",
            "summary": "",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Konstruktor",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method___construct"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003Apozdrav\u0028\u0029",
            "name": "pozdrav",
            "summary": "test\u0020funkcnosti",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method_pozdrav"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003Avek\u0028\u0029",
            "name": "vek",
            "summary": "funkcepro\u0020vypocet\u0020veku\u0020z\u0020data\u0020narozeni",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method_vek"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003ApridejNovehoUzivatele\u0028\u0029",
            "name": "pridejNovehoUzivatele",
            "summary": "zapise\u0020zvalidovane\u0020udaje\u0020noveho\u0020uzivatele\u0020do\u0020databaze",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method_pridejNovehoUzivatele"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003ApridejEditovanehoUzivatele\u0028\u0029",
            "name": "pridejEditovanehoUzivatele",
            "summary": "zapise\u0020zvalidovane\u0020udaje\u0020editovaneho\u0020uzivatele\u0020do\u0020databaze",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method_pridejEditovanehoUzivatele"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003AinfoPanel\u0028\u0029",
            "name": "infoPanel",
            "summary": "info\u0020panel\u0020vypsany\u0020po\u0020prihlaseni",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method_infoPanel"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003Aucet\u0028\u0029",
            "name": "ucet",
            "summary": "info\u0020panel\u0020vypsany\u0020po\u0020prihlaseni\u0020informujici\u0020o\nzakldnich\u0020udajich\u0020registrovaneho\u0020v\u0020databazi",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method_ucet"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003AvypisKontraktu\u0028\u0029",
            "name": "vypisKontraktu",
            "summary": "info\u0020vypsany\u0020po\u0020prihlaseni\u0020informujici\u0020uzivatele\u0020o\u0020jeho\nuzavrenych\u0020kontraktech\u0020ulozenych\u0020v\u0020databazi",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method_vypisKontraktu"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003AucetEdit\u0028\u0029",
            "name": "ucetEdit",
            "summary": "editace\u0020uzivatele\u0020zapsaneho\u0020v\u0020databazi\nuzivatel\u0020edituje\u0020jen\u0020svuj\u0020ucet\nadministrator\u0020edituje\u0020svuj\u0020ucet\u0020a\u0020ucty\u0020vsech\u0020registrovanych\nvypise\u0020uzivatele\u0020z\u0020databaze\nvygeneruje\u0020formular\u0020pro\u0020odeslani\u0020ID\u0020uzivatele\u0020kter\u00FD\u0020bude\u0020editovan",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method_ucetEdit"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003AucetEditUloz\u0028\u0029",
            "name": "ucetEditUloz",
            "summary": "editace\u0020uzivatele\u0020zapsaneho\u0020v\u0020databazi\nuzivatel\u0020edituje\u0020jen\u0020svuj\u0020ucet\nadministrator\u0020edituje\u0020svuj\u0020ucet\u0020a\u0020ucty\u0020vsech\u0020registrovanych\npodle\u0020ID\u0020odeslaneho\u0020z\u0020formulare\u0020vypise\u0020do\u0020editacniho\u0020formulare\nudaje\u0020uzivatele\u0020pro\u0020editaci",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method_ucetEditUloz"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003AucetAdmin\u0028\u0029",
            "name": "ucetAdmin",
            "summary": "vypis\u0020evidovanych\u0020uzivatelu\nz\u0020databaze",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method_ucetAdmin"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003Aodstran\u0028\u0029",
            "name": "odstran",
            "summary": "odstrani\u0020uzivatele\u0020z\u0020databaze\u0020na\u0020zaklade\u0020ID\na\u0020popripade\u0020odstrani\u0020kotrakty\u0020vazajici\u0020se\u0020k\nuzivateli\u0020dle\u0020jeho\u0020ID",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method_odstran"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003AodstranVybrane\u0028\u0029",
            "name": "odstranVybrane",
            "summary": "odstrani\u0020hromadne\u0020vybrane\u0020uzivatele\u0020z\u0020databaze\u0020na\u0020zaklade\u0020ID\na\u0020popripade\u0020odstrani\u0020kotrakty\u0020vazajici\u0020se\u0020k\nuzivateli\u0020dle\u0020jeho\u0020ID",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method_odstranVybrane"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003AvypisVsechnyKontrakty\u0028\u0029",
            "name": "vypisVsechnyKontrakty",
            "summary": "info\u0020vypsany\u0020po\u0020prihlaseni\u0020informujici\u0020aministratora\u0020o\nuzavrenych\u0020kontraktech\u0020ulozenych\u0020v\u0020databazi",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method_vypisVsechnyKontrakty"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003AodstranKontrakt\u0028\u0029",
            "name": "odstranKontrakt",
            "summary": "odstrani\u0020kontrakt\u0020z\u0020databaze\u0020na\u0020zaklade\u0020ID",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method_odstranKontrakt"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003AeditujKontrakt\u0028\u0029",
            "name": "editujKontrakt",
            "summary": "odstrani\u0020kontrakt\u0020z\u0020databaze\u0020na\u0020zaklade\u0020ID",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method_editujKontrakt"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003AhledejKontrakt\u0028\u0029",
            "name": "hledejKontrakt",
            "summary": "odstrani\u0020kontrakt\u0020z\u0020databaze\u0020na\u0020zaklade\u0020ID",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method_hledejKontrakt"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "test",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#method___toString"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003A\u0024identifikace",
            "name": "identifikace",
            "summary": "",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#property_identifikace"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003A\u0024prijmeni",
            "name": "prijmeni",
            "summary": "",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#property_prijmeni"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003A\u0024datum_narozeni",
            "name": "datum_narozeni",
            "summary": "",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#property_datum_narozeni"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#property_email"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003A\u0024telefon",
            "name": "telefon",
            "summary": "",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#property_telefon"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003A\u0024ulece",
            "name": "ulece",
            "summary": "",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#property_ulece"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003A\u0024mesto",
            "name": "mesto",
            "summary": "",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#property_mesto"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003A\u0024psc",
            "name": "psc",
            "summary": "",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#property_psc"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003A\u0024heslo",
            "name": "heslo",
            "summary": "",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#property_heslo"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#property_id"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003A\u0024statut",
            "name": "statut",
            "summary": "",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#property_statut"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003A\u0024jmeno",
            "name": "jmeno",
            "summary": "",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#property_jmeno"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele\\Uzivatel\u003A\u003A\u0024identUzivatele",
            "name": "identUzivatele",
            "summary": "",
            "url": "classes/Zaklad-adminUzivatele-Uzivatel.html#property_identUzivatele"
        },                {
            "fqsen": "\\Zaklad\\Html\\Form",
            "name": "Form",
            "summary": "",
            "url": "classes/Zaklad-Html-Form.html"
        },                {
            "fqsen": "\\Zaklad\\Html\\Form\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Zaklad-Html-Form.html#method___construct"
        },                {
            "fqsen": "\\Zaklad\\Html\\Form\u003A\u003Atest\u0028\u0029",
            "name": "test",
            "summary": "",
            "url": "classes/Zaklad-Html-Form.html#method_test"
        },                {
            "fqsen": "\\Zaklad\\Html\\Form\u003A\u003Aform\u0028\u0029",
            "name": "form",
            "summary": "",
            "url": "classes/Zaklad-Html-Form.html#method_form"
        },                {
            "fqsen": "\\Zaklad\\Html\\Form\u003A\u003AInput_pole\u0028\u0029",
            "name": "Input_pole",
            "summary": "",
            "url": "classes/Zaklad-Html-Form.html#method_Input_pole"
        },                {
            "fqsen": "\\Zaklad\\Html\\Form\u003A\u003Abutton\u0028\u0029",
            "name": "button",
            "summary": "",
            "url": "classes/Zaklad-Html-Form.html#method_button"
        },                {
            "fqsen": "\\Zaklad\\Html\\Form\u003A\u003A\u0024akce",
            "name": "akce",
            "summary": "",
            "url": "classes/Zaklad-Html-Form.html#property_akce"
        },                {
            "fqsen": "\\Zaklad\\Html\\Form\u003A\u003A\u0024metoda",
            "name": "metoda",
            "summary": "",
            "url": "classes/Zaklad-Html-Form.html#property_metoda"
        },                {
            "fqsen": "\\Zaklad\\Html\\Form\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Zaklad-Html-Form.html#property_id"
        },                {
            "fqsen": "\\Zaklad\\Html\\Form\u003A\u003A\u0024popis",
            "name": "popis",
            "summary": "",
            "url": "classes/Zaklad-Html-Form.html#property_popis"
        },                {
            "fqsen": "\\Zaklad\\Html\\Form\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Zaklad-Html-Form.html#property_type"
        },                {
            "fqsen": "\\Zaklad\\Html\\Form\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Zaklad-Html-Form.html#property_name"
        },                {
            "fqsen": "\\Zaklad\\Html\\Form\u003A\u003A\u0024hodnota",
            "name": "hodnota",
            "summary": "",
            "url": "classes/Zaklad-Html-Form.html#property_hodnota"
        },                {
            "fqsen": "\\Zaklad\\Html\\KratkyText",
            "name": "KratkyText",
            "summary": "",
            "url": "classes/Zaklad-Html-KratkyText.html"
        },                {
            "fqsen": "\\Zaklad\\Html\\KratkyText\u003A\u003AkratkyVypis\u0028\u0029",
            "name": "kratkyVypis",
            "summary": "",
            "url": "classes/Zaklad-Html-KratkyText.html#method_kratkyVypis"
        },                {
            "fqsen": "\\Zaklad\\Html\\KratkyText\u003A\u003A\u0024strucne",
            "name": "strucne",
            "summary": "",
            "url": "classes/Zaklad-Html-KratkyText.html#property_strucne"
        },                {
            "fqsen": "\\Zaklad\\Html\\ListovaniEasy",
            "name": "ListovaniEasy",
            "summary": "",
            "url": "classes/Zaklad-Html-ListovaniEasy.html"
        },                {
            "fqsen": "\\Zaklad\\Html\\ListovaniEasy\u003A\u003Alistuj\u0028\u0029",
            "name": "listuj",
            "summary": "jednoduche\u0020listovani\u0020v\u0020DB\nmetoda\u0020GET",
            "url": "classes/Zaklad-Html-ListovaniEasy.html#method_listuj"
        },                {
            "fqsen": "\\Zaklad\\Html\\ListovaniEasy\u003A\u003AvratOdRadku\u0028\u0029",
            "name": "vratOdRadku",
            "summary": "",
            "url": "classes/Zaklad-Html-ListovaniEasy.html#method_vratOdRadku"
        },                {
            "fqsen": "\\Zaklad\\Html\\ListovaniEasy\u003A\u003AvratKolikRadku\u0028\u0029",
            "name": "vratKolikRadku",
            "summary": "",
            "url": "classes/Zaklad-Html-ListovaniEasy.html#method_vratKolikRadku"
        },                {
            "fqsen": "\\Zaklad\\Html\\ListovaniEasy\u003A\u003AvratInfo\u0028\u0029",
            "name": "vratInfo",
            "summary": "",
            "url": "classes/Zaklad-Html-ListovaniEasy.html#method_vratInfo"
        },                {
            "fqsen": "\\Zaklad\\Html\\ListovaniEasy\u003A\u003A\u0024pocet_zaznamu",
            "name": "pocet_zaznamu",
            "summary": "",
            "url": "classes/Zaklad-Html-ListovaniEasy.html#property_pocet_zaznamu"
        },                {
            "fqsen": "\\Zaklad\\Html\\ListovaniEasy\u003A\u003A\u0024pocet_vypisu",
            "name": "pocet_vypisu",
            "summary": "",
            "url": "classes/Zaklad-Html-ListovaniEasy.html#property_pocet_vypisu"
        },                {
            "fqsen": "\\Zaklad\\Html\\ListovaniEasy\u003A\u003A\u0024cti_od_radku",
            "name": "cti_od_radku",
            "summary": "",
            "url": "classes/Zaklad-Html-ListovaniEasy.html#property_cti_od_radku"
        },                {
            "fqsen": "\\Zaklad\\Html\\ListovaniEasy\u003A\u003A\u0024str",
            "name": "str",
            "summary": "",
            "url": "classes/Zaklad-Html-ListovaniEasy.html#property_str"
        },                {
            "fqsen": "\\Zaklad\\Html\\Test",
            "name": "Test",
            "summary": "",
            "url": "classes/Zaklad-Html-Test.html"
        },                {
            "fqsen": "\\Zaklad\\Html\\Test\u003A\u003Apozdraveni\u0028\u0029",
            "name": "pozdraveni",
            "summary": "",
            "url": "classes/Zaklad-Html-Test.html#method_pozdraveni"
        },                {
            "fqsen": "\\Zaklad\\Html\\Validace",
            "name": "Validace",
            "summary": "",
            "url": "classes/Zaklad-Html-Validace.html"
        },                {
            "fqsen": "\\Zaklad\\Html\\Validace\u003A\u003AvalidujPrihlaseni\u0028\u0029",
            "name": "validujPrihlaseni",
            "summary": "",
            "url": "classes/Zaklad-Html-Validace.html#method_validujPrihlaseni"
        },                {
            "fqsen": "\\Zaklad\\Html\\Validace\u003A\u003AvalidujRegistraci\u0028\u0029",
            "name": "validujRegistraci",
            "summary": "",
            "url": "classes/Zaklad-Html-Validace.html#method_validujRegistraci"
        },                {
            "fqsen": "\\Zaklad\\Html\\Validace\u003A\u003AvalidujObjednavku\u0028\u0029",
            "name": "validujObjednavku",
            "summary": "",
            "url": "classes/Zaklad-Html-Validace.html#method_validujObjednavku"
        },                {
            "fqsen": "\\Zaklad\\Html\\Validace\u003A\u003A\u0024zprava",
            "name": "zprava",
            "summary": "",
            "url": "classes/Zaklad-Html-Validace.html#property_zprava"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Zaklad\\adminProdukt",
            "name": "adminProdukt",
            "summary": "",
            "url": "namespaces/zaklad-adminprodukt.html"
        },                {
            "fqsen": "\\Zaklad",
            "name": "Zaklad",
            "summary": "",
            "url": "namespaces/zaklad.html"
        },                {
            "fqsen": "\\Zaklad\\adminUzivatele",
            "name": "adminUzivatele",
            "summary": "",
            "url": "namespaces/zaklad-adminuzivatele.html"
        },                {
            "fqsen": "\\Zaklad\\Html",
            "name": "Html",
            "summary": "",
            "url": "namespaces/zaklad-html.html"
        }            ]
);
